name: CI/CD HealthTrack System

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    # CI/CD Workflow para HealthTrack System - por Victor Figueroa
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium pytest pytest-html
          pip install -e .

      - name: Instalar Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          google-chrome --version

      - name: Preparar carpeta pública
        run: |
          mkdir -p public
          cp formulario_usuario.html public/

      - name: Levantar servidor HTTP para el formulario
        run: |
          cd public
          nohup python3 -m http.server 8000 &
          sleep 5

      - name: Run unit tests
        run: |
          pytest tests/unit --maxfail=1 --disable-warnings -q

      - name: Run functional tests (Selenium)
        run: |
          PYTHONPATH=./src pytest tests/functional --maxfail=1 --disable-warnings -q

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Victfigueroa_healthtrack-system
            -Dsonar.organization=victfigueroa
            -Dsonar.host.url=https://sonarcloud.io
