name: CI/CD HealthTrack System

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

      web:
        image: python:3.13
        ports:
          - 8000:8000
        volumes:
          - .:/app
        working-directory: /app/public
        command: python -m http.server 8000

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install selenium pytest pytest-html
        pip install -e .

    - name: Preparar carpeta pública
      run: |
        mkdir -p public
        cp formulario_usuario.html public/

    - name: Run unit tests
      run: |
        pytest tests/unit --maxfail=1 --disable-warnings -q

    - name: Run functional tests (Selenium)
      env:
        SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
      run: |
        PYTHONPATH=./src pytest --rootdir=. tests/functional --maxfail=1 --disable-warnings -q

    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=healthtrack-system
          -Dsonar.organization=victfigueroa
          -Dsonar.host.url=https://sonarcloud.io
